[build]
publish = "/"
command = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
framework = "#custom"
command = "python3 -m http.server 8000"
targetPort = 8000
port = 8888
publish = "/"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net; img-src 'self' data: blob:; connect-src 'self'"
